// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8CZhXvhrj9_Dn_t-CuN9ssDY-fBJhzsw',
    appId: '1:886736618280:web:a553b5228ee39fe357c61d',
    messagingSenderId: '886736618280',
    projectId: 'cookeasy-538d7',
    authDomain: 'cookeasy-538d7.firebaseapp.com',
    storageBucket: 'cookeasy-538d7.firebasestorage.app',
    measurementId: 'G-RFPQE002JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcWkHWccr2zsvMIiduBCYBRSVG-5CYZPc',
    appId: '1:886736618280:android:0a1fbdf0c3a448de57c61d',
    messagingSenderId: '886736618280',
    projectId: 'cookeasy-538d7',
    storageBucket: 'cookeasy-538d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxGyO75t6Fls5g33Mf7_EsnGAnH2317s',
    appId: '1:886736618280:ios:13a98b40c863dc4f57c61d',
    messagingSenderId: '886736618280',
    projectId: 'cookeasy-538d7',
    storageBucket: 'cookeasy-538d7.firebasestorage.app',
    iosBundleId: 'com.example.cookeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxGyO75t6Fls5g33Mf7_EsnGAnH2317s',
    appId: '1:886736618280:ios:13a98b40c863dc4f57c61d',
    messagingSenderId: '886736618280',
    projectId: 'cookeasy-538d7',
    storageBucket: 'cookeasy-538d7.firebasestorage.app',
    iosBundleId: 'com.example.cookeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8CZhXvhrj9_Dn_t-CuN9ssDY-fBJhzsw',
    appId: '1:886736618280:web:34857bf20cbad36957c61d',
    messagingSenderId: '886736618280',
    projectId: 'cookeasy-538d7',
    authDomain: 'cookeasy-538d7.firebaseapp.com',
    storageBucket: 'cookeasy-538d7.firebasestorage.app',
    measurementId: 'G-NGNTEX9WVL',
  );
}
